# Generated by Django 3.0 on 2019-12-16 03:39

from django.db import migrations


def create_shop_data(apps, schema_editor):
    """ creates some fake shop data for use in the application """
    Cart = apps.get_model('shopping_cart_core', 'Cart')
    Item = apps.get_model('shopping_cart_core', 'Item')

    Cart.objects.create()

    Item.objects.create(
        name="Tesla Cybertruck",
        description="BETTER UTILITY THAN A TRUCK WITH MORE PERFORMANCE THAN A SPORTS CAR",
        price=39995.0,
        thumbnail_key='cybertruck'
    )
    Item.objects.create(
        name="HDMI Cable",
        description="Just a regular HDMI cable.",
        price=19.99,
        thumbnail_key='hdmi'
    )
    Item.objects.create(
        name="Maruchan Instant Ramen, Chicken",
        description="Delicious, nutritious Ramen. Just what the doctor ordered.",
        price=0.99,
        thumbnail_key='ramen'
    )
    Item.objects.create(
        name="White T-shirt",
        description="It's a t-shirt, hooray!",
        price=8.99,
        thumbnail_key='shirt'
    )
    Item.objects.create(
        name="Nintendo Switch",
        description="Fully-featured for home and on-the-go gaming.",
        price=299.99,
        thumbnail_key='switch'
    )
    Item.objects.create(
        name="Apple iPhone 11 Pro",
        description="A transformative triple‑camera system that adds tons of capability without complexity. An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro.",
        price=599.0,
        thumbnail_key='iphone'
    )
    Item.objects.create(
        name="Bicycle",
        description="A somehow totally brandless bicycle.",
        price=149.99,
        thumbnail_key='bicycle'
    )
    Item.objects.create(
        name="Atlantic Salmon (One Pound)",
        description="One Pound of fresh-caught Atlantic Salmon. Because why not?",
        price=7.99,
        thumbnail_key='salmon'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart_core', '0001_initial')
    ]

    operations = [
        migrations.RunPython(create_shop_data)
    ]
